// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Registration.Infrastructure.Persistence;

namespace Registration.Infrastructure.Persistence.Migrations;

/// <inheritdoc />
[DbContext(typeof(RegistrationDbContext))]
[Migration("20260421000000_InitialRegistration")]
public sealed partial class InitialRegistration
{
}
