// <auto-generated />
#nullable enable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Registration.Infrastructure.Persistence;

namespace Registration.Infrastructure.Persistence.Migrations;

/// <inheritdoc />
[DbContext(typeof(RegistrationDbContext))]
public sealed partial class RegistrationDbContextModelSnapshot : ModelSnapshot
{
    /// <inheritdoc />
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("registration")
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("Registration.Application.Sagas.RegistrationSagaState", b =>
        {
            b.Property<Guid>("CorrelationId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("correlation_id");

            b.Property<Guid?>("AccountId")
                .HasColumnType("uuid")
                .HasColumnName("account_id");

            b.Property<string>("AssociationName")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("association_name");

            b.Property<DateTimeOffset?>("CompletedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("completed_at");

            b.Property<string>("Currency")
                .IsRequired()
                .HasMaxLength(3)
                .HasColumnType("character(3)")
                .HasColumnName("currency");

            b.Property<string>("CurrentState")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)")
                .HasColumnName("current_state");

            b.Property<string?>("FailureReason")
                .HasMaxLength(2048)
                .HasColumnType("character varying(2048)")
                .HasColumnName("failure_reason");

            b.Property<string>("PrimaryUserEmail")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("primary_user_email");

            b.Property<Guid?>("ReportingId")
                .HasColumnType("uuid")
                .HasColumnName("reporting_id");

            b.Property<DateTimeOffset>("StartedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("started_at");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("tenant_id");

            b.Property<Guid?>("UserId")
                .HasColumnType("uuid")
                .HasColumnName("user_id");

            b.HasKey("CorrelationId")
                .HasName("pk_registration_saga_state");

            b.HasIndex("CurrentState")
                .HasDatabaseName("ix_registration_saga_state_current_state");

            b.ToTable("registration_saga_state", "registration");
        });
#pragma warning restore 612, 618
    }
}
