using Chassis.Host.Configuration;

WebApplicationBuilder builder = WebApplication.CreateBuilder(args);
builder.AddChassisHost();

WebApplication app = builder.Build();
app.UseChassisPipeline();

await app.RunAsync().ConfigureAwait(false);

// Expose a partial Program class so WebApplicationFactory<Program> can reference it
// from the integration test project (which has InternalsVisibleTo access).
// The class itself is compiler-generated by the top-level statements above; this
// partial declaration simply ensures the type is accessible from test assemblies.
namespace Chassis.Host
{
    /// <summary>
    /// Partial extension of the compiler-generated Program class so integration tests
    /// can reference it via <c>WebApplicationFactory&lt;Program&gt;</c>.
    /// </summary>
    public partial class Program
    {
    }
}
