// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reporting.Infrastructure.Persistence;

#nullable disable

namespace Reporting.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ReportingDbContext))]
partial class ReportingDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        // TransactionProjection
        modelBuilder.Entity("Reporting.Application.Persistence.TransactionProjection", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid");

            b.Property<Guid>("SourceMessageId")
                .HasColumnType("uuid");

            b.Property<Guid>("AccountId")
                .HasColumnType("uuid");

            b.Property<decimal>("Amount")
                .HasColumnType("numeric(19,4)");

            b.Property<string>("Currency")
                .IsRequired()
                .HasColumnType("char(3)");

            b.Property<DateTimeOffset>("OccurredAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("TenantId", "Id")
                .HasDatabaseName("IX_transaction_projections_TenantId_Id");

            b.HasIndex("TenantId", "SourceMessageId")
                .IsUnique()
                .HasDatabaseName("ix_transaction_projections_tenant_source_message");

            b.ToTable("transaction_projections", "reporting");
        });

        // MassTransit InboxState
        modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

            b.Property<string>("Consumer")
                .IsRequired()
                .HasColumnType("text");

            b.Property<DateTimeOffset?>("Delivered")
                .HasColumnType("timestamp with time zone");

            b.Property<DateTimeOffset?>("ExpirationTime")
                .HasColumnType("timestamp with time zone");

            b.Property<long?>("LastSequenceNumber")
                .HasColumnType("bigint");

            b.Property<Guid>("MessageId")
                .HasColumnType("uuid");

            b.Property<int>("ReceiveCount")
                .HasColumnType("integer");

            b.Property<byte[]>("RowVersion")
                .IsConcurrencyToken()
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("bytea");

            b.HasKey("Id");
            b.HasAlternateKey("MessageId", "Consumer");
            b.HasIndex("Delivered");
            b.HasIndex("ExpirationTime");

            b.ToTable("InboxState", "reporting");
        });

        // MassTransit OutboxMessage
        modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
        {
            b.Property<long>("SequenceNumber")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

            b.Property<string>("Body").IsRequired().HasColumnType("text");
            b.Property<string>("ContentType").IsRequired().HasColumnType("text");
            b.Property<Guid?>("ConversationId").HasColumnType("uuid");
            b.Property<Guid?>("CorrelationId").HasColumnType("uuid");
            b.Property<DateTimeOffset?>("EnqueueTime").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset?>("ExpirationTime").HasColumnType("timestamp with time zone");
            b.Property<string>("FaultAddress").HasColumnType("text");
            b.Property<string>("Headers").HasColumnType("text");
            b.Property<string>("InboxConsumer").HasColumnType("text");
            b.Property<Guid?>("InboxMessageId").HasColumnType("uuid");
            b.Property<Guid?>("InitiatorId").HasColumnType("uuid");
            b.Property<Guid>("MessageId").HasColumnType("uuid");
            b.Property<string>("MessageType").IsRequired().HasColumnType("text");
            b.Property<Guid?>("OutboxId").HasColumnType("uuid");
            b.Property<string>("Properties").HasColumnType("text");
            b.Property<Guid?>("RequestId").HasColumnType("uuid");
            b.Property<string>("ResponseAddress").HasColumnType("text");
            b.Property<DateTimeOffset>("SentTime").HasColumnType("timestamp with time zone");
            b.Property<string>("SourceAddress").HasColumnType("text");
            b.Property<string>("DestinationAddress").HasColumnType("text");

            b.HasKey("SequenceNumber");
            b.HasIndex("EnqueueTime");
            b.HasIndex("ExpirationTime");
            b.HasIndex("OutboxId", "SequenceNumber");

            b.ToTable("OutboxMessage", "reporting");
        });

        // MassTransit OutboxState
        modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
        {
            b.Property<Guid>("OutboxId").HasColumnType("uuid");
            b.Property<DateTimeOffset>("Created").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset?>("Delivered").HasColumnType("timestamp with time zone");
            b.Property<long?>("LastSequenceNumber").HasColumnType("bigint");
            b.Property<Guid>("LockId").HasColumnType("uuid");
            b.Property<byte[]>("LockToken").HasColumnType("bytea");
            b.Property<byte[]>("RowVersion")
                .IsConcurrencyToken()
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("bytea");

            b.HasKey("OutboxId");
            b.ToTable("OutboxState", "reporting");
        });
#pragma warning restore 612, 618
    }
}
