-- =============================================================================
-- Migration: 001_initial_registration
-- Target: registration schema + registration_saga_state table
-- Author: generated by AI-assisted development (Phase 5)
-- Applied: idempotent — safe to run multiple times
-- =============================================================================

-- Create schema
CREATE SCHEMA IF NOT EXISTS registration;

-- =============================================================================
-- Table: registration.registration_saga_state
-- =============================================================================
-- RLS EXEMPTION NOTE:
-- This table intentionally does NOT have Row-Level Security (RLS) enabled.
-- The saga orchestrates the provisioning of a new tenant, meaning the tenant
-- being created does NOT yet exist in the system when the saga starts. There is
-- no tenant context to filter on, so RLS cannot meaningfully protect this table.
-- Access control is enforced at the application layer:
--   1. The saga is only created by the registration endpoint.
--   2. The saga state is queried only by MassTransit's saga repository (infrastructure).
--   3. Saga correlation IDs are randomly generated UUIDs — not guessable.
-- Any future admin query endpoint must enforce application-level authorization.
-- =============================================================================
CREATE TABLE IF NOT EXISTS registration.registration_saga_state
(
    correlation_id     uuid         NOT NULL,
    current_state      varchar(64)  NOT NULL DEFAULT 'Initial',
    tenant_id          uuid         NOT NULL,
    association_name   varchar(256) NOT NULL,
    primary_user_email varchar(256) NOT NULL,
    currency           char(3)      NOT NULL,
    user_id            uuid,
    account_id         uuid,
    reporting_id       uuid,
    started_at         timestamptz  NOT NULL,
    completed_at       timestamptz,
    failure_reason     varchar(2048),
    CONSTRAINT pk_registration_saga_state PRIMARY KEY (correlation_id)
);

-- Index on current_state for health dashboards, monitoring queries, and saga active-count gauge.
CREATE INDEX IF NOT EXISTS ix_registration_saga_state_current_state
    ON registration.registration_saga_state (current_state);

-- =============================================================================
-- EF Core migrations history (enables EF dotnet-ef tooling for this schema)
-- =============================================================================
CREATE TABLE IF NOT EXISTS registration.__ef_migrations_history
(
    migration_id    varchar(150) NOT NULL,
    product_version varchar(32)  NOT NULL,
    CONSTRAINT pk_ef_migrations_history_registration PRIMARY KEY (migration_id)
);
