using System.Collections.Generic;

namespace Ai.Contracts;

/// <summary>Roles permitted in a chat turn.</summary>
public enum ChatRole
{
    /// <summary>System instruction injected before the conversation.</summary>
    System,

    /// <summary>Message authored by the end-user.</summary>
    User,

    /// <summary>Message generated by the language model.</summary>
    Assistant,

    /// <summary>Result of a tool / function call returned to the model.</summary>
    Tool,
}

/// <summary>A single message in a chat conversation.</summary>
public sealed class ChatMessage
{
    /// <summary>Gets or sets the author role for this message.</summary>
    public ChatRole Role { get; set; }

    /// <summary>Gets or sets the text content of the message.</summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the tool call identifier when <see cref="Role"/> is <see cref="ChatRole.Tool"/>.
    /// </summary>
    public string? ToolCallId { get; set; }

    /// <summary>
    /// Gets or sets arbitrary tool-call details (name, arguments) when the model requests a tool call.
    /// </summary>
    public IReadOnlyList<ToolCall>? ToolCalls { get; set; }
}

/// <summary>A tool call issued by the model inside an assistant message.</summary>
public sealed class ToolCall
{
    /// <summary>Gets or sets the provider-assigned tool call identifier.</summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>Gets or sets the tool function name.</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>Gets or sets the raw JSON arguments for the tool function.</summary>
    public string ArgumentsJson { get; set; } = string.Empty;
}
