// <auto-generated />
// This file is a manually-authored snapshot to avoid running dotnet-ef in the build step.
// Regenerate by running:
//   dotnet ef migrations add <Name> --project Ledger.Infrastructure --startup-project Chassis.Host
using System;
using Ledger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ledger.Infrastructure.Persistence.Migrations;

[DbContext(typeof(LedgerDbContext))]
partial class LedgerDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Ledger.Domain.Entities.Account", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasColumnType("char(3)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("TenantId", "Id");

                b.ToTable("accounts", "ledger");
            });

        modelBuilder.Entity("Ledger.Domain.Entities.Posting", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("AccountId")
                    .HasColumnType("uuid");

                b.Property<Guid?>("IdempotencyKey")
                    .HasColumnType("uuid");

                b.Property<string>("Memo")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<DateTimeOffset>("OccurredAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("AccountId");

                b.HasIndex("TenantId", "IdempotencyKey")
                    .IsUnique()
                    .HasDatabaseName("ix_postings_tenant_idempotency_key")
                    .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                b.ToTable("postings", "ledger");
            });

        modelBuilder.Entity("Ledger.Domain.Entities.Account", b =>
            {
                b.OwnsMany("Ledger.Domain.Entities.Posting", "Postings", b1 =>
                    {
                    });

                b.Navigation("Postings");
            });

        modelBuilder.Entity("Ledger.Domain.Entities.Posting", b =>
            {
                b.HasOne("Ledger.Domain.Entities.Account", null)
                    .WithMany("Postings")
                    .HasForeignKey("AccountId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.OwnsOne("Ledger.Domain.ValueObjects.Money", "Amount", b1 =>
                    {
                        b1.Property<Guid>("PostingId")
                            .HasColumnType("uuid");

                        b1.Property<decimal>("Amount")
                            .HasColumnType("numeric(19,4)")
                            .HasColumnName("amount");

                        b1.Property<string>("Currency")
                            .IsRequired()
                            .HasColumnType("char(3)")
                            .HasColumnName("currency");

                        b1.HasKey("PostingId");

                        b1.ToTable("postings", "ledger");

                        b1.WithOwner()
                            .HasForeignKey("PostingId");
                    });

                b.Navigation("Amount")
                    .IsRequired();
            });

        // MassTransit OutboxMessage
        modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
            {
                b.Property<long>("SequenceNumber")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                b.Property<string>("Body").IsRequired().HasColumnType("text");
                b.Property<string>("ContentType").IsRequired().HasColumnType("text");
                b.Property<Guid?>("ConversationId").HasColumnType("uuid");
                b.Property<Guid?>("CorrelationId").HasColumnType("uuid");
                b.Property<DateTimeOffset?>("EnqueueTime").HasColumnType("timestamp with time zone");
                b.Property<DateTimeOffset?>("ExpirationTime").HasColumnType("timestamp with time zone");
                b.Property<string>("FaultAddress").HasColumnType("text");
                b.Property<string>("Headers").HasColumnType("text");
                b.Property<string>("InboxConsumer").HasColumnType("text");
                b.Property<Guid?>("InboxMessageId").HasColumnType("uuid");
                b.Property<Guid?>("InitiatorId").HasColumnType("uuid");
                b.Property<Guid>("MessageId").HasColumnType("uuid");
                b.Property<string>("MessageType").IsRequired().HasColumnType("text");
                b.Property<Guid?>("OutboxId").HasColumnType("uuid");
                b.Property<string>("Properties").HasColumnType("text");
                b.Property<Guid?>("RequestId").HasColumnType("uuid");
                b.Property<string>("ResponseAddress").HasColumnType("text");
                b.Property<DateTimeOffset>("SentTime").HasColumnType("timestamp with time zone");
                b.Property<string>("SourceAddress").HasColumnType("text");
                b.Property<string>("DestinationAddress").HasColumnType("text");

                b.HasKey("SequenceNumber");
                b.HasIndex("EnqueueTime");
                b.HasIndex("ExpirationTime");
                b.HasIndex("OutboxId", "SequenceNumber");

                b.ToTable("OutboxMessage", "ledger");
            });

        // MassTransit OutboxState
        modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
            {
                b.Property<Guid>("OutboxId").HasColumnType("uuid");
                b.Property<DateTimeOffset>("Created").HasColumnType("timestamp with time zone");
                b.Property<DateTimeOffset?>("Delivered").HasColumnType("timestamp with time zone");
                b.Property<long?>("LastSequenceNumber").HasColumnType("bigint");
                b.Property<Guid>("LockId").HasColumnType("uuid");
                b.Property<byte[]>("LockToken").HasColumnType("bytea");
                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("bytea");

                b.HasKey("OutboxId");
                b.ToTable("OutboxState", "ledger");
            });
#pragma warning restore 612, 618
    }
}
